version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: meeting-ai-postgres
    environment:
      POSTGRES_USER: meeting_ai
      POSTGRES_PASSWORD: dev_password_123
      POSTGRES_DB: meeting_ai_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/sql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U meeting_ai -d meeting_ai_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - meeting-ai-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: meeting-ai-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    healthcheck:
      test: ["CMD", "sh", "-c", 'redis-cli -a "$$REDIS_PASSWORD" PING | grep PONG']
      interval: 5s
      timeout: 3s
      retries: 10
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - meeting-ai-network

  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    container_name: meeting-ai-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: dev_minio_password_123
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - meeting-ai-network

  # pgAdmin (PostgreSQL Web Interface)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: meeting-ai-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@meeting-ai.dev
      PGADMIN_DEFAULT_PASSWORD: admin_password_123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - meeting-ai-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  meeting-ai-network:
    driver: bridge
