"""add_idempotent_key_column_to_transcripts

Revision ID: 8f6d3c7fd583
Revises: da5864a08adb
Create Date: 2025-08-29 23:37:57.354894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f6d3c7fd583'
down_revision: Union[str, Sequence[str], None] = 'da5864a08adb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('idempotent_key', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_transcripts_idempotent_key'), 'transcripts', ['idempotent_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcripts_idempotent_key'), table_name='transcripts')
    op.drop_column('transcripts', 'idempotent_key')
    # ### end Alembic commands ###
